### ISSUE TITLE
No client ip_address?

### ISSUE THREAD

**Issue by kazerewrite** [muzuiget/mitmpcap#4]
When I use the addon, it shows these information:
Addon error: Traceback (most recent call last):
  File "c:\Program Files (x86)\mitmproxy\mitmpcap.py", line 114, in response
    client_addr = list(flow.client_conn.ip_address[:2])
AttributeError: 'Client' object has no attribute 'ip_address'

How can I fix it?

**Comment by lhlhx** [comment]
I changed line 114 and 115 as below and it seems worked for me.
Disclaimer: I did not do a regression test on the code.
```
        client_addr = list(flow.client_conn.peername[:2])
        server_addr = list(flow.server_conn.peername[:2])
```

Cheers

**Comment by inceabdullah** [comment]
> I changed line 114 and 115 as below and it seems worked for me. Disclaimer: I did not do a regression test on the code.
> 
> ```
>         client_addr = list(flow.client_conn.peername[:2])
>         server_addr = list(flow.server_conn.peername[:2])
> ```
> 
> Cheers

I have added PR: https://github.com/muzuiget/mitmpcap/pull/9

Thank you @lhlhx

**Comment by raxod502** [comment]
Even with that PR, I get:

```
AttributeError: 'ServerConnection' object has no attribute 'peername'
```

**Comment by lhlhx** [comment]
How is your PCAP setup? @raxod502

**Comment by raxod502** [comment]
What do you mean? I don't have a PCAP file; I have a dump file produced by mitmproxy, which I'm trying to convert into PCAP format.

**Comment by lhlhx** [comment]
@raxod502 apologize for my wordings, I mean how is your mitmproxy capture setup?

**Comment by inceabdullah** [comment]
> @raxod502 apologize for my wordings, I mean how is your mitmproxy capture setup?

I thing with the param `-s` like:
`-s mitmpcap.py`

but I always set `save.py` also.

**Comment by raxod502** [comment]
Yes, correct, I was using:

```sh
mitmproxy -nr preexisting.dump -s mitmpcap.py
```

to read a dump file that was previously exported by mitmproxy.

I have subsequently learned that the version of mitmproxy shipped in recent Ubuntu versions is very old (6.x), and have since upgraded (9.x). With the latest version, the version of mitmpcap in this repository does not work, but the updated version suggested in https://github.com/muzuiget/mitmpcap/issues/4#issuecomment-1144171881 does.

**Comment by muzuiget** [comment]
#10
